# ----------------#
#  systrayUpdater #
# ----------------#

# Terminal emulator launch command and execute option
terminal: $TERM
option: -e
# timer value is set to minutes
timer: 10
# custom icons should follow Arch linux standards
# custom icons should be stored in ~/.config/systrayUpdater
icon: arch-white-symbolic-24.svg
