#  systrayUpdater #
# ----------------#
# Terminal emulator launch command and execute option
terminal: $TERM
option: -e
# timer value is set to minutes
timer: 10
# Icons can be set to pre-defined colors:  red, purple, blue, green, yellow, white, gray and black
# Custom icons should be placed in "~/.config/systrayupdater" and file name provided
icon: white
